---
title: "Parallel Trends Test"
author: "David A. Lee"
date: '2023-02-14'
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

setwd("/Users/davidalee/Documents/David A. Lee/CUNY John Jay Documents/ECO 799 - Seminar/Parallel Trends Test")

waterdata <- read.csv(file = 'Water_Transfer_Data_Feb_10.csv')

```

```{r rename col}

library("tidyverse")

waterdata <- as.tibble(waterdata)

waterdata <- waterdata[-1,]

waterdata <- waterdata %>% 
  rename(
    "IDCode" = X, # ID Code
    "Year" = X.1, # Year
    "State" = X.2, # State 
    "MinYrAF" = Quantity.of.Water.Transferred, # Minimum Average Acre-Foot
    "AvgYrAF" = X.3, # Average Annual Acre-Feet
    "MaxYrAF" = X.4, # Maximum Annual Acre-Feet
    "ComMinAF" = X.5, # Committed Minimum Acre-Feet
    "ComAvgAF" = X.6, # Committed Average Acre-Feeet
    "ComMaxAF" = X.7, # Committed Maximum Acre-Feet
    "TotalPrice" = Prices, # Total Price
    "InfAdjTP" = X.8, # Inflation Adjusted Total Price
    "InfAdjPperYrAF" = X.9, # Inflation Adjusted Price per Annual Acre-Foot
    "InfAdjPperComAF" = X.10, # Inflation Adjusted Price per Committed Acre-Foot
    "Sale" = Transfer.Length, # Sale
    "Lease" = X.11, # Lease
    "Exchange" = X.12, # Exchange
    "Lease Duration" = X.13, # Lease Duration
    "AgAg" = Transfer.Type, # Ag-to-Ag
    "AgUrban" = X.14, # Ag-to-Urban
    "AgEnv" = X.15, # Ag-to-Enviro
    "UrbAg" = X.16, # Urban-to-Ag
    "UrbUrb" = X.17, # Urban-to-Urban
    "UrbEnv" = X.18, # Urban-to-Enviro
    "EnvAg" = X.19, # Enviro-to-Ag
    "EnvUrb" = X.20, # Enviro-to-Urban
    "EnvEnv" = X.21, # Enviro-to-Enviro
    "Comb" = X.22, # Combination
    "Recyc" = X.23, # Recycled
    "Unknown" = X.24, # Unknown
    "Seller" = X.25, # Seller
    "Buyer" = X.26, # Buyer
    "WStratIss" = X.27 # Water Strategist Issue
    )

```

```{r removenan}

waterdata <- waterdata[-which(waterdata$InfAdjPperYrAF == ""), ]

# The data I will be using in the scripts below is the Inflation Adjusted Price per Acre-Foot, defined by Libecap and Donehew as "A continuous variable of the inflation adjusted total price divided by the annual flow amount of water transferred." This is because the NQH2O price index is in units of USD/acre-foot. Here, the inflation-adjusted prices are given in 1987 dollars. 

# Question: How to work with inflation-adjusted price data?



```

```{r AZCA}

# Test code for 1987

AZ1987 <- waterdata$InfAdjPperYrAF[waterdata$State== "AZ" & waterdata$Year==1987]
AZ1987 <- as.numeric(AZ1987)
mean(AZ1987)
sd(AZ1987)
cev_AZ1987 <- sd(AZ1987) / mean(AZ1987)

# For-loop for Arizona, 1987-2009

AZ_data <- c()

for( i in c(1987:2009)){ 
  AZ_yr_cev <- sd(as.numeric(waterdata$InfAdjPperYrAF[waterdata$State== "AZ" & waterdata$Year== i])) / mean(as.numeric(waterdata$InfAdjPperYrAF[waterdata$State== "AZ" & waterdata$Year== i]))
  AZ_data <- c(AZ_data, AZ_yr_cev)
}

print(AZ_data)

# For-loop for California, 1987-2009

CA_data <- c()

for( i in c(1987:2009)){ 
  CA_yr_cev <- sd(as.numeric(gsub(",","",waterdata$InfAdjPperYrAF[waterdata$State== "CA" & waterdata$Year== i]))) / mean(as.numeric(gsub(",","",waterdata$InfAdjPperYrAF[waterdata$State== "CA" & waterdata$Year== i])))
  CA_data <- c(CA_data, CA_yr_cev)
}

print(CA_data)

```

```{r ggplot AZCA}

library(ggplot2)

AZ <- data.frame(Year=c(1987:2009),CEV=as.numeric(AZ_data))
CA <- data.frame(Year=c(1987:2009),CEV=as.numeric(CA_data))

AZCA <- AZ %>%  mutate(Type = 'Arizona') %>%
       bind_rows(CA %>%
           mutate(Type = 'California'))


AZCAplot <- ggplot(AZCA,aes(y = CEV,x = Year,color = Type)) + 
  geom_line() +
  geom_point() +
  ggtitle("Coefficient of Variation Time Series, AZ and CA")

```

```{r NVCA}

# For-loop for Nevada, 1987-2009

NV_data <- c()

for( i in c(1987:2009)){ 
  NV_yr_cev <- sd(as.numeric(gsub(",","",waterdata$InfAdjPperYrAF[waterdata$State== "NV" & waterdata$Year== i]))) / mean(as.numeric(gsub(",","",waterdata$InfAdjPperYrAF[waterdata$State== "NV" & waterdata$Year== i])))
  NV_data <- c(NV_data, NV_yr_cev)
}

print(NV_data)

```

```{r ggplot NVCA}

NV <- data.frame(Year=c(1987:2009),CEV=as.numeric(NV_data))
CA <- data.frame(Year=c(1987:2009),CEV=as.numeric(CA_data))

NVCA <- NV %>%  mutate(Type = 'Nevada') %>%
       bind_rows(CA %>%
           mutate(Type = 'California'))


NVCAplot <- ggplot(NVCA,aes(y = CEV,x = Year,color = Type)) + 
  geom_line() +
  geom_point() +
  ggtitle("Coefficient of Variation Time Series, NV and CA")

```

```{r ORCA}

# For-loop for Oregon, 1987-2009

OR_data <- c()

for( i in c(1987:2009)){ 
  OR_yr_cev <- sd(as.numeric(gsub(",","",waterdata$InfAdjPperYrAF[waterdata$State== "OR" & waterdata$Year== i]))) / mean(as.numeric(gsub(",","",waterdata$InfAdjPperYrAF[waterdata$State== "OR" & waterdata$Year== i])))
  OR_data <- c(OR_data, OR_yr_cev)
}

print(OR_data)

```
```{r ggplot ORCA}

OR <- data.frame(Year=c(1987:2009),CEV=as.numeric(OR_data))
CA <- data.frame(Year=c(1987:2009),CEV=as.numeric(CA_data))

ORCA <- OR %>%  mutate(Type = 'Oregon') %>%
       bind_rows(CA %>%
           mutate(Type = 'California'))


ORCAplot <- ggplot(ORCA,aes(y = CEV,x = Year,color = Type)) + 
  geom_line() +
  geom_point() +
  ggtitle("Coefficient of Variation Time Series, OR and CA")

```

```{r WACA}

# For-loop for Washington, 1987-2009

WA_data <- c()

for( i in c(1987:2009)){ 
  WA_yr_cev <- sd(as.numeric(gsub(",","",waterdata$InfAdjPperYrAF[waterdata$State== "WA" & waterdata$Year== i]))) / mean(as.numeric(gsub(",","",waterdata$InfAdjPperYrAF[waterdata$State== "WA" & waterdata$Year== i])))
  WA_data <- c(WA_data, WA_yr_cev)
}

print(WA_data)

```
```{r ggplot WACA}

WA <- data.frame(Year=c(1987:2009),CEV=as.numeric(WA_data))
CA <- data.frame(Year=c(1987:2009),CEV=as.numeric(CA_data))

WACA <- WA %>%  mutate(Type = 'Washington') %>%
       bind_rows(CA %>%
           mutate(Type = 'California'))


WACAplot <- ggplot(WACA,aes(y = CEV,x = Year,color = Type)) + 
  geom_line() +
  geom_point() +
  ggtitle("Coefficient of Variation Time Series, WA and CA")

```

```{r IDCA}

# For-loop for Idaho, 1987-2009

ID_data <- c()

for( i in c(1987:2009)){ 
  ID_yr_cev <- sd(as.numeric(gsub(",","",waterdata$InfAdjPperYrAF[waterdata$State== "ID" & waterdata$Year== i]))) / mean(as.numeric(gsub(",","",waterdata$InfAdjPperYrAF[waterdata$State== "ID" & waterdata$Year== i])))
  ID_data <- c(ID_data, ID_yr_cev)
}

print(ID_data)

```
```{r ggplot IDCA}

ID <- data.frame(Year=c(1987:2009),CEV=as.numeric(ID_data))
CA <- data.frame(Year=c(1987:2009),CEV=as.numeric(CA_data))

IDCA <- ID %>%  mutate(Type = 'Idaho') %>%
       bind_rows(CA %>%
           mutate(Type = 'California'))


IDCAplot <- ggplot(IDCA,aes(y = CEV,x = Year,color = Type)) + 
  geom_line() +
  geom_point() +
  ggtitle("Coefficient of Variation Time Series, ID and CA")

```

```{r UTCA}

# For-loop for Utah, 1987-2009

UT_data <- c()

for( i in c(1987:2009)){ 
  UT_yr_cev <- sd(as.numeric(gsub(",","",waterdata$InfAdjPperYrAF[waterdata$State== "UT" & waterdata$Year== i]))) / mean(as.numeric(gsub(",","",waterdata$InfAdjPperYrAF[waterdata$State== "UT" & waterdata$Year== i])))
  UT_data <- c(UT_data, UT_yr_cev)
}

print(UT_data)

```
```{r ggplot UTCA}

UT <- data.frame(Year=c(1987:2009),CEV=as.numeric(UT_data))
CA <- data.frame(Year=c(1987:2009),CEV=as.numeric(CA_data))

UTCA <- UT %>%  mutate(Type = 'Utah') %>%
       bind_rows(CA %>%
           mutate(Type = 'California'))


UTCAplot <- ggplot(UTCA,aes(y = CEV,x = Year,color = Type)) + 
  geom_line() +
  geom_point() +
  ggtitle("Coefficient of Variation Time Series, UT and CA")

```

```{r MTCA}

# For-loop for Montana, 1987-2009

MT_data <- c()

for( i in c(1987:2009)){ 
  MT_yr_cev <- sd(as.numeric(gsub(",","",waterdata$InfAdjPperYrAF[waterdata$State== "MT" & waterdata$Year== i]))) / mean(as.numeric(gsub(",","",waterdata$InfAdjPperYrAF[waterdata$State== "MT" & waterdata$Year== i])))
  MT_data <- c(MT_data, MT_yr_cev)
}

print(MT_data)

```

```{r ggplot MTCA}

MT <- data.frame(Year=c(1987:2009),CEV=as.numeric(MT_data))
CA <- data.frame(Year=c(1987:2009),CEV=as.numeric(CA_data))

MTCA <- MT %>%  mutate(Type = 'Montana') %>%
       bind_rows(CA %>%
           mutate(Type = 'California'))


MTCAplot <- ggplot(MTCA,aes(y = CEV,x = Year,color = Type)) + 
  geom_line() +
  geom_point() +
  ggtitle("Coefficient of Variation Time Series, MT and CA")

```

```{r WYCA}

# For-loop for Wyoming, 1987-2009

WY_data <- c()

for( i in c(1987:2009)){ 
  WY_yr_cev <- sd(as.numeric(gsub(",","",waterdata$InfAdjPperYrAF[waterdata$State== "WY" & waterdata$Year== i]))) / mean(as.numeric(gsub(",","",waterdata$InfAdjPperYrAF[waterdata$State== "WY" & waterdata$Year== i])))
  WY_data <- c(WY_data, WY_yr_cev)
}

print(WY_data)

```

```{r ggplot WYCA}

WY <- data.frame(Year=c(1987:2009),CEV=as.numeric(WY_data))
CA <- data.frame(Year=c(1987:2009),CEV=as.numeric(CA_data))

WYCA <- WY %>%  mutate(Type = 'Wyoming') %>%
       bind_rows(CA %>%
           mutate(Type = 'California'))


WYCAplot <- ggplot(WYCA,aes(y = CEV,x = Year,color = Type)) + 
  geom_line() +
  geom_point() +
  ggtitle("Coefficient of Variation Time Series, WY and CA")

```

```{r COCA}

# For-loop for Colorado, 1987-2009

CO_data <- c()

for( i in c(1987:2009)){ 
  CO_yr_cev <- sd(as.numeric(gsub(",","",waterdata$InfAdjPperYrAF[waterdata$State== "CO" & waterdata$Year== i]))) / mean(as.numeric(gsub(",","",waterdata$InfAdjPperYrAF[waterdata$State== "CO" & waterdata$Year== i])))
  CO_data <- c(CO_data, CO_yr_cev)
}

print(CO_data)

```

```{r ggplot COCA}

CO <- data.frame(Year=c(1987:2009),CEV=as.numeric(CO_data))
CA <- data.frame(Year=c(1987:2009),CEV=as.numeric(CA_data))

COCA <- CO %>%  mutate(Type = 'Colorado') %>%
       bind_rows(CA %>%
           mutate(Type = 'California'))


COCAplot <- ggplot(COCA,aes(y = CEV,x = Year,color = Type)) + 
  geom_line() +
  geom_point() +
  ggtitle("Coefficient of Variation Time Series, CO and CA")

```

```{r NMCA}

# For-loop for New Mexico, 1987-2009

NM_data <- c()

for( i in c(1987:2009)){ 
  NM_yr_cev <- sd(as.numeric(gsub(",","",waterdata$InfAdjPperYrAF[waterdata$State== "NM" & waterdata$Year== i]))) / mean(as.numeric(gsub(",","",waterdata$InfAdjPperYrAF[waterdata$State== "NM" & waterdata$Year== i])))
  NM_data <- c(NM_data, NM_yr_cev)
}

print(NM_data)

```

```{r ggplot NMCA}

NM <- data.frame(Year=c(1987:2009),CEV=as.numeric(NM_data))
CA <- data.frame(Year=c(1987:2009),CEV=as.numeric(CA_data))

NMCA <- NM %>%  mutate(Type = 'New Mexico') %>%
       bind_rows(CA %>%
           mutate(Type = 'California'))


NMCAplot <- ggplot(NMCA,aes(y = CEV,x = Year,color = Type)) + 
  geom_line() +
  geom_point() +
  ggtitle("Coefficient of Variation Time Series, NM and CA")

```

```{r TXCA}

# For-loop for Texas, 1987-2009

TX_data <- c()

for( i in c(1987:2009)){ 
  TX_yr_cev <- sd(as.numeric(gsub(",","",waterdata$InfAdjPperYrAF[waterdata$State== "TX" & waterdata$Year== i]))) / mean(as.numeric(gsub(",","",waterdata$InfAdjPperYrAF[waterdata$State== "TX" & waterdata$Year== i])))
  TX_data <- c(TX_data, TX_yr_cev)
}

print(TX_data)

```

```{r ggplot TXCA}

TX <- data.frame(Year=c(1987:2009),CEV=as.numeric(TX_data))
CA <- data.frame(Year=c(1987:2009),CEV=as.numeric(CA_data))

TXCA <- TX %>%  mutate(Type = 'Texas') %>%
       bind_rows(CA %>%
           mutate(Type = 'California'))


TXCAplot <- ggplot(TXCA,aes(y = CEV,x = Year,color = Type)) + 
  geom_line() +
  geom_point() +
  ggtitle("Coefficient of Variation Time Series, TX and CA")

```

```{r graph matrix}

AZCAplot

par(mfrow = c(5,2))

NVCAplot
ORCAplot
WACAplot
IDCAplot
UTCAplot
MTCAplot
WYCAplot
COCAplot
NMCAplot
TXCAplot

```
```{r NQH2O Time series}

Velesdata <- read.csv(file = 'Veles.csv')

Velesdata <- as.tibble(Velesdata)

Velesdata <- Velesdata %>% 
  rename(
    "CEV" = Monthly.volatility..std.mean.
  )


Velesplot <- ggplot(Velesdata,aes(y = CEV,x = Time.Index)) + 
  geom_line() +
  scale_x_continuous(breaks=seq(1, 90, 3)) +
  geom_point() +
  ggtitle("CEV Time Series of NQH2O Index Prices, CA, 9/2019-2/2022")

Velesplot

```

